spring:
  rabbitmq:
#    RabbitProperties里面默认的其实就是localhost
    host: localhost
#    默认的用户名和密码就是guest,默认的端口就是5672，virtual-host默认的是/
#    username: guest
#    password: guest
    port: 5672
    virtual-host: /
